// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
	TRelationship extends
		| prismic.CustomTypeModelFetchCustomTypeLevel1
		| prismic.CustomTypeModelFetchCustomTypeLevel2
		| prismic.CustomTypeModelFetchGroupLevel1
		| prismic.CustomTypeModelFetchGroupLevel2,
	TData extends Record<
		string,
		prismic.AnyRegularField | prismic.GroupField | prismic.NestedGroupField | prismic.SliceZone
	>,
	TLang extends string
> =
	// Content relationship fields
	{
		[TSubRelationship in Extract<
			TRelationship['fields'][number],
			prismic.CustomTypeModelFetchContentRelationshipLevel1
		> as TSubRelationship['id']]: ContentRelationshipFieldWithData<
			TSubRelationship['customtypes'],
			TLang
		>;
	} & // Group
	{
		[TGroup in Extract<
			TRelationship['fields'][number],
			prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2
		> as TGroup['id']]: TData[TGroup['id']] extends prismic.GroupField<infer TGroupData>
			? prismic.GroupField<PickContentRelationshipFieldData<TGroup, TGroupData, TLang>>
			: never;
	} & // Other fields
	{
		[TFieldKey in Extract<TRelationship['fields'][number], string>]: TFieldKey extends keyof TData
			? TData[TFieldKey]
			: never;
	};

type ContentRelationshipFieldWithData<
	TCustomType extends
		| readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
		| readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
	TLang extends string = string
> = {
	[ID in Exclude<TCustomType[number], string>['id']]: prismic.ContentRelationshipField<
		ID,
		TLang,
		PickContentRelationshipFieldData<
			Extract<TCustomType[number], { id: ID }>,
			Extract<prismic.Content.AllDocumentTypes, { type: ID }>['data'],
			TLang
		>
	>;
}[Exclude<TCustomType[number], string>['id']];

/**
 * Content for brownie insert documents
 */
interface BrownieInsertDocumentData {
	/**
	 * Brownie Insert field in *brownie insert*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: brownie_insert.brownie_insert
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	brownie_insert: prismic.ImageField<never>;
}

/**
 * brownie insert document from Prismic
 *
 * - **API ID**: `brownie_insert`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BrownieInsertDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<BrownieInsertDocumentData>,
	'brownie_insert',
	Lang
>;

/**
 * Content for cake base documents
 */
interface CakeBaseDocumentData {
	/**
	 * Cake Base field in *cake base*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cake_base.cake_base
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	cake_base: prismic.ImageField<never>;
}

/**
 * cake base document from Prismic
 *
 * - **API ID**: `cake_base`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CakeBaseDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<CakeBaseDocumentData>,
	'cake_base',
	Lang
>;

/**
 * Content for cake flavours documents
 */
interface CakeFlavoursDocumentData {
	/**
	 * Cake Flavours field in *cake flavours*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cake_flavours.cake_flavours
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	cake_flavours: prismic.ImageField<never>;
}

/**
 * cake flavours document from Prismic
 *
 * - **API ID**: `cake_flavours`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CakeFlavoursDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<CakeFlavoursDocumentData>,
	'cake_flavours',
	Lang
>;

/**
 * Content for cake toppings documents
 */
interface CakeToppingsDocumentData {
	/**
	 * Cake Toppings field in *cake toppings*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cake_toppings.cake_toppings
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	cake_toppings: prismic.ImageField<never>;
}

/**
 * cake toppings document from Prismic
 *
 * - **API ID**: `cake_toppings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CakeToppingsDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<CakeToppingsDocumentData>,
	'cake_toppings',
	Lang
>;

/**
 * Content for cupcake insert documents
 */
interface CupcakeInsertDocumentData {
	/**
	 * Cupcake Insert field in *cupcake insert*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cupcake_insert.cupcake_insert
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	cupcake_insert: prismic.ImageField<never>;
}

/**
 * cupcake insert document from Prismic
 *
 * - **API ID**: `cupcake_insert`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CupcakeInsertDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<CupcakeInsertDocumentData>,
	'cupcake_insert',
	Lang
>;

/**
 * Content for delivery Insert documents
 */
interface DeliveryInsertDocumentData {
	/**
	 * Delivery Insert field in *delivery Insert*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: delivery_insert.delivery_insert
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	delivery_insert: prismic.ImageField<never>;
}

/**
 * delivery Insert document from Prismic
 *
 * - **API ID**: `delivery_insert`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DeliveryInsertDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithoutUID<Simplify<DeliveryInsertDocumentData>, 'delivery_insert', Lang>;

/**
 * Item in *recent → Card*
 */
export interface RecentDocumentDataCardItem {
	/**
	 * item field in *recent → Card*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: recent.card[].item
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	item: prismic.ImageField<never>;

	/**
	 * description field in *recent → Card*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: recent.card[].description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;

	/**
	 * Button Link field in *recent → Card*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: recent.card[].button_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	button_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for recent documents
 */
interface RecentDocumentData {
	/**
	 * Card field in *recent*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: recent.card[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	card: prismic.GroupField<Simplify<RecentDocumentDataCardItem>>;
}

/**
 * recent document from Prismic
 *
 * - **API ID**: `recent`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RecentDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<RecentDocumentData>,
	'recent',
	Lang
>;

/**
 * Item in *review → Review*
 */
export interface ReviewDocumentDataReviewItem {
	/**
	 * Name field in *review → Review*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Customer name
	 * - **API ID Path**: review.review[].name
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	name: prismic.RichTextField;

	/**
	 * Quote field in *review → Review*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Their review
	 * - **API ID Path**: review.review[].quote
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	quote: prismic.RichTextField;
}

/**
 * Content for review documents
 */
interface ReviewDocumentData {
	/**
	 * Review field in *review*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: review.review[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	review: prismic.GroupField<Simplify<ReviewDocumentDataReviewItem>>;
}

/**
 * review document from Prismic
 *
 * - **API ID**: `review`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ReviewDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<ReviewDocumentData>,
	'review',
	Lang
>;

export type AllDocumentTypes =
	| BrownieInsertDocument
	| CakeBaseDocument
	| CakeFlavoursDocument
	| CakeToppingsDocument
	| CupcakeInsertDocument
	| DeliveryInsertDocument
	| RecentDocument
	| ReviewDocument;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	interface CreateWriteClient {
		(
			repositoryNameOrEndpoint: string,
			options: prismic.WriteClientConfig
		): prismic.WriteClient<AllDocumentTypes>;
	}

	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			BrownieInsertDocument,
			BrownieInsertDocumentData,
			CakeBaseDocument,
			CakeBaseDocumentData,
			CakeFlavoursDocument,
			CakeFlavoursDocumentData,
			CakeToppingsDocument,
			CakeToppingsDocumentData,
			CupcakeInsertDocument,
			CupcakeInsertDocumentData,
			DeliveryInsertDocument,
			DeliveryInsertDocumentData,
			RecentDocument,
			RecentDocumentData,
			RecentDocumentDataCardItem,
			ReviewDocument,
			ReviewDocumentData,
			ReviewDocumentDataReviewItem,
			AllDocumentTypes
		};
	}
}
