// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *recent → Card*
 */
export interface RecentDocumentDataCardItem {
	/**
	 * item field in *recent → Card*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: recent.card[].item
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	item: prismic.ImageField<never>;

	/**
	 * description field in *recent → Card*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: recent.card[].description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;

	/**
	 * Button Link field in *recent → Card*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: recent.card[].button_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	button_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for recent documents
 */
interface RecentDocumentData {
	/**
	 * Card field in *recent*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: recent.card[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	card: prismic.GroupField<Simplify<RecentDocumentDataCardItem>>;
}

/**
 * recent document from Prismic
 *
 * - **API ID**: `recent`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RecentDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<RecentDocumentData>,
	'recent',
	Lang
>;

export type AllDocumentTypes = RecentDocument;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	interface CreateWriteClient {
		(
			repositoryNameOrEndpoint: string,
			options: prismic.WriteClientConfig
		): prismic.WriteClient<AllDocumentTypes>;
	}

	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			RecentDocument,
			RecentDocumentData,
			RecentDocumentDataCardItem,
			AllDocumentTypes
		};
	}
}
